### ISSUE TITLE
wrfhydro Preprocessor: opening netcdf's in QGIS

### ISSUE THREAD

**Issue by gwaihir8** [NCAR/wrf_hydro_arcgis_preprocessor#11] opened 2019-04-04 09:56 UTC
Hi,

I see that the Fulldom_hires.nc follows CF-compliancy, but I can't seem to get them in the correct location in QGIS.. I see this as crs.spatial_ref attribute:

`PROJCS["Sphere_Mercator",GEOGCS["GCS_Sphere",DATUM["D_Sphere",SPHEROID["Sphere",6370000.0,0.0]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Mercator"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",8.0],PARAMETER["Standard_Parallel_1",53.5],UNIT["Meter",1.0]];-11903700 -17965200 10000;-100000 10000;-100000 10000;0,001;0,001;0,001;IsHighPrecision`

Which CRS do I need to indicate in QGIS to get the data at the right location?

thanks!

Kobe

**Comment by kmsampson** [comment] 2019-04-09 03:24
The WKT you provided above is the CRS that you will need to use in GIS applications. If you prefer the proj.4 notation, the Fulldom_hires.nc file also includes a global attribute ".proj4". You can use this string in QGIS to manually define your project's coordinate system. However, I find that I can just drag and drop a Fulldom_hires.nc file into QGIS and it will automatically allow me to select the variables I wish to add to the display and render them with the proper geo-location.

**Comment by kmsampson** [comment] 2019-10-11 15:10
Closing, assuming the issue is resolved on the user's end.

**Closed** 2019-10-11 15:09 UTC
